spring:
  thymeleaf:
    cache: false
  datasource:
    username: mrone
    password: 123456
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update
      freemarker:
        suffix: .ftl
        settings:
          classic_compatible: true
      redis:
        database: 0
        port: 6379
        password: 123456
        host: localhost
      elasticsearch:
        uris: 127.0.0.1:9200
        username:
        password:
#    wechat:
#      mpAppId: wx990dc5a6f0f8c2f4
#      mpAppSecret: 7b75e3f0dd5c8ec9bd12d635032488c5
#      token: 11355084
#    server:
#      domain: http://zvknu6.natappfree.cc
#  &allowPublicKeyRetrieval=true

mybatis-plus:
  type-aliases-package: com.study.entity
  mapper-locations: classpath:mapper/*Mapper.xml
server:
  port: 9090